//
//  PasteboardMonitor.swift
//  Cutling: auto-captures NSPasteboard changes into CutlingStore history.
//
//  macOS has no pasteboard-change notification API. We poll changeCount on a
//  Timer (the same approach used by Maccy). 500ms is the Maccy / PlainPasta
//  middle ground: snappy enough for UX, light on CPU.
//

#if os(macOS)
import AppKit
import Foundation

@MainActor
final class PasteboardMonitor {
    private weak var store: CutlingStore?
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    private(set) var isRunning = false

    /// Pasteboard types we never capture: set by password managers and other
    /// apps that flag their content as sensitive or transient. Names are
    /// well-known conventions (see nspasteboard.org and 1Password/Bitwarden).
    private let ignoredTypeNames: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.apple.is-sensitive",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
    ]

    init(store: CutlingStore) {
        self.store = store
        self.lastChangeCount = pasteboard.changeCount
    }

    func start() {
        guard !isRunning else { return }
        isRunning = true
        lastChangeCount = pasteboard.changeCount
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in self?.tick() }
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        isRunning = false
    }

    /// Mark the current pasteboard changeCount as already-seen, so the next
    /// tick treats it as a no-op. Called by the picker after it writes to
    /// the pasteboard so picking an item doesn't echo back into history.
    func acknowledgeCurrentPasteboardChange() {
        lastChangeCount = pasteboard.changeCount
    }

    private func tick() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current
        guard let store else { return }
        guard !shouldIgnoreCurrentContents() else { return }
        captureCurrentContents(into: store)
    }

    private func shouldIgnoreCurrentContents() -> Bool {
        let items = pasteboard.pasteboardItems ?? []
        for item in items {
            for type in item.types where ignoredTypeNames.contains(type.rawValue) {
                return true
            }
        }
        return false
    }

    private func captureCurrentContents(into store: CutlingStore) {
        if let text = pasteboard.string(forType: .string),
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            store.appendHistoryText(text)
            return
        }
        for type in [NSPasteboard.PasteboardType.png, .tiff] {
            if let data = pasteboard.data(forType: type), !data.isEmpty {
                store.appendHistoryImage(data, sourceFilename: imageFilenameFromPasteboard())
                return
            }
        }
    }

    /// When the user copies an image file from Finder, the pasteboard
    /// carries a `fileURL`; lift the last path component as the display
    /// name. Raw screenshot-to-clipboard captures don't expose a URL, so
    /// nil here tells the store to synthesise a date-based name.
    private func imageFilenameFromPasteboard() -> String? {
        let options: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
        guard let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: options) as? [URL],
              let url = urls.first else { return nil }
        let name = url.lastPathComponent
        return name.isEmpty ? nil : name
    }
}
#endif
